services:
  - type: web
    name: gemini-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:8080 app:app
    envVars:
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}

  - type: web
    name: gemini-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://gemini-backend.onrender.com
